### ISSUE TITLE
Node.js 16.x is the current Long Term Support (LTS)

### ISSUE THREAD

**Issue by fabiel-leon** [aws/aws-lambda-base-images#33] opened 2021-12-29 22:23 UTC
https://nodejs.org/en/ 

implement this in a new base image please :pray:

**Comment by alexbaileyuk** [comment] 2022-01-01 23:58
Duplicate of https://github.com/aws/aws-lambda-base-images/issues/14

**Comment by y4my4my4m** [comment] 2022-01-04 23:58
@carlzogh @krk 
Sorry to ping you guys directly, but is there any information on this?
I've searched and searched and it seems that there is zero information out there for developers.
AWS is too big to be leaving developers in the dark like this.

Thank you

**Comment by rawpixel-vincent** [comment] 2022-03-22 20:29
> AWS is too big to be leaving developers in the dark like this.

AWS is big enough to leave developers in the dark like this.

**Comment by dl748** [comment] 2022-04-12 20:36
Placeholder for closed issue #14

**Comment by DavidTanner** [comment] 2022-04-25 16:35
https://github.com/aws/aws-lambda-base-images/issues/14#issuecomment-1108679026

```
Thank you everyone for the continued engagement and feedback on this issue. The AWS Lambda Node 16 runtime implementation is in progress, and we are currently on track to launch in mid-May. Our Node 16 runtime will continue to use AWS SDKv2, and we plan to transition to AWS SDKv3 with Node 18.
```

**Closed** 2022-08-18 13:40 UTC
Labels: nodejs
