### ISSUE TITLE
python:3.11 image ImportError: libffi.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by alynlee** [aws/aws-lambda-base-images#129] opened 2023-12-07 01:41 UTC
I am reaching out to seek your assistance regarding an issue we encountered during the deployment of a Lambda function, where we utilized the "latest" tag for the public.ecr.aws/lambda/python:3.11 image. We have temporarily addressed the problem by modifying the hash value. I would appreciate it if you could help us confirm the following details.

**Comment by jtuliani** [comment] 2023-12-08 16:30
Closing as duplicate of #127 and #128. Please re-try with the latest Python 3.11 image. Please re-open with more details if the issue persists.

**Closed as completed by jtuliani** 2023-12-08 16:30 UTC
